export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_ARTICLE = "FETCH_ARTICLE";
export const FETCH_AUTHOR_ARTICLES = "FETCH_AUTHOR_ARTICLES";

export const FETCH_AUTHORS = "FETCH_AUTHORS";
export const FETCH_AUTHOR = "FETCH_AUTHOR";
